FILES = get_object.py			load_ucondb.py			put_object_cb.py		put_objects_http.py \
	create_folder.py		get_object_cb.py		put_object.py			put_object_http_signature.py	ui.py

build:	$(BINDIR)
	cp $(FILES) $(BINDIR)
	
$(BINDIR):
	mkdir -p $@